# fly.toml app configuration file generated for radio-pad-registry on 2025-07-20T17:11:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radio-pad-registry'
primary_region = 'den'

[build]

[env]
  AWS_ROLE_ARN = 'arn:aws:iam::531273887830:role/registry.radiopad.dev'
  REGISTRY_BACKEND = 's3'
  REGISTRY_BACKEND_S3_BUCKET = 'registry.radiopad.dev'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '8s'
    method = 'GET'
    path = '/healthz'

[[restart]]
  policy = 'always'
  retries = 3

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
