# fly.toml app configuration file generated for radio-pad-registry on 2025-07-20T17:11:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radio-pad-registry'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '3s'
    method = 'GET'
    path = '/healthz'

[[restart]]
  policy = 'always'
  retries = 3

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
