[tool.isort]
profile = "black"

[tool.pytest.ini_options]
# Ignore DeprecationWarnings. These stem from Connexion.
# Connexion is limited to OpenAPI 3.0 support at the time of this writing.
# OpenAPI 3.1 allows for newer JSON Schema drafts which pytest will not warn about.

#filterwarnings = [
#    "ignore::DeprecationWarning"
#]

