openapi: "3.0.0"

info:
  title: RadioPad Registry API
  version: "0.0.0"
servers:
  - url: /v1

paths:
  /players/{player_id}:
    get:
      summary: Get Player
      description: Returns a RadioPad Player by its ID.
      parameters:
        - name: player_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the player to retrieve.
      responses:
        '200':
          description: Player details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
            application/xml:
              schema:
                $ref: '#/components/schemas/Player'
                xml:
                  name: player
                  wrapped: true
        '404':
          description: Player not found
  /players/{player_id}/stations:
    get:
      summary: Get Player Stations
      description: Returns the stations for a specific RadioPad Player.
      operationId: api.players.get_stations
      parameters:
        - name: player_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the player to retrieve stations for.
      responses:
        '200':
          description: List of stations for the player
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
        '404':
          description: Player not found
  /players:
    get:
      summary: List Players
      description: Returns a list of RadioPad Players.
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PerPage'
      responses:
        '200':
          description: List of players with pagination metadata
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/_Pagination'
                - type: object
                  properties:
                    items:
                      type: array
                      description: List of PlayerSummary objects
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            example: foo
                          name:
                            type: string
                            example: Foo Player

components:
  parameters:
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Page number of the results to fetch.
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      description: Number of items per page.

  schemas:
    _Pagination:
      type: object
      properties:
        page:
          type: integer
          description: Current page number
        per_page:
          type: integer
          description: Number of items per page
        total:
          type: integer
          description: Total number of items
        total_pages:
          type: integer
          description: Total number of pages
      required: [page, per_page, total, total_pages]
    Player:
      type: object
      properties:
        id:
          type: string
          example: foo
        name:
          type: string
          example: bonjour foo
        stationsUrl:
          type: string
          format: uri
          example: https://registry.radiopad.dev/players/foo/stations.json
        switchboardUrl:
          type: string
          format: uri
          example: wss://foo.player-switchboard.radiopad.dev
    Station:
      type: object
      properties:
        name:
          type: string
          example: wwoz
        url:
          type: string
          format: uri
          example: https://www.wwoz.org/listen/hi
