openapi: "3.0.0"

info:
  title: RadioPad Registry API
  version: "0.0.0"
servers:
  - url: /v1

x-pagination-params: &paginationParams
    - $ref: '#/components/parameters/Page'
    - $ref: '#/components/parameters/PerPage'

paths:
  /players/{id}:
    get:
      tags: [Players]
      summary: Get Player
      description: Returns a RadioPad Player by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the player to retrieve.
      responses:
        '200':
          description: Player details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '404':
          $ref: '#/components/responses/NotFound'
  /players:
    get:
      tags: [Players]
      summary: List Players
      description: Returns a list of RadioPad Players.
      parameters: *paginationParams
      responses:
        '200':
          description: List of paginated Players
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/_PaginatedResponse'
                  - type: object
                    properties:
                      items:
                        $ref: '#/components/schemas/PlayerList'

  /station-presets/{id}:
    get:
      tags: [Stations]
      summary: Get Stations for a Preset
      description: Returns the stations for a specific Preset ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the station preset to retrieve stations for.
      responses:
        '200':
          description: List of stations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationList'
        '404':
          $ref: '#/components/responses/NotFound'

  /station-presets:
    get:
      tags: [Stations]
      summary: List Station Presets
      description: Returns a list of available station presets.
      parameters: *paginationParams
      responses:
        '200':
          description: List of paginated Station Presets
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/_PaginatedResponse'
                  - type: object
                    properties:
                      items:
                        $ref: '#/components/schemas/StationPresetList'

components:
  parameters:
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Page number of the results to fetch.
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      description: Number of items per page.

  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Not Found
  schemas:
    Player:
      $ref: './schemas/Player.json#/definitions/Player'
      
    PlayerList:
      $ref: './schemas/PlayerList.json#/definitions/PlayerList'

    StationList:
      $ref: './schemas/StationList.json#/definitions/StationList'

    StationPreset:
      $ref: './schemas/StationPreset.json#/definitions/StationPreset'

    StationPresetList:
      $ref: './schemas/StationPresetList.json#/definitions/StationPresetList'

    _PaginatedResponse:
      type: object
      properties:
        items:
          type: array
          description: List of items in the current page
          items: {}
        page:
          type: integer
          description: Current page number
        per_page:
          type: integer
          description: Number of items per page
        total:
          type: integer
          description: Total number of items
        total_pages:
          type: integer
          description: Total number of pages
      required: [page, per_page, total, total_pages]

