openapi: "3.0.0"

info:
  title: RadioPad Registry
  version: "0.0.0"
servers:
  - url: /

paths:
  /players:
    get:
      summary: List RadioPad Players
      description: Returns a list of players.
      operationId: registry.get_players
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerList'
            application/xml:
              schema:
                $ref: '#/components/schemas/PlayerList'

components:
  schemas:
    PlayerList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: foo
          name:
            type: string
            example: Foo Player
